### ISSUE TITLE
Faltan archivos

### ISSUE THREAD

**Issue by jmwielandt** [LinoBigatti/GBAPM#1]
Hola, cuando lo voy a ejecutar me sale esto:
![image](https://user-images.githubusercontent.com/37153467/52525735-b843b780-2c8c-11e9-8460-b7ba70a1895b.png)

Atte.
Jasón

PD: migra a 3.7 (?)

**Comment by LinoBigatti** [comment]
Efectivamente, a compumax tambien le sucede. No se la causa del error, pero estoy esperando que el compile un ejecutable para usarlo como parche. Compilar desde la fuente arregla este problema.
PD: No puedo, debo mantenerme en 3.6 si quiero un ejecutable :(

**Comment by LinoBigatti** [comment]
Ya encontre el error! Deberia funcionar bien ahora, en el ultimo parche.
